# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
   image: postgres
   restart: always
   environment:
    POSTGRES_USER: ryanbanco
    POSTGRES_PASSWORD: abc123
    POSTGRES_DB: test
   ports:
    - "5432:5432"
